"use client";

import React, { use, useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { 
  loadReports, 
  loadStudents, 
  loadAssessments,
  loadFacultyProfile, 
  ReportLog,
  Student,
  Assessment
} from "@/lib/storage";
import { 
  ArrowLeft, 
  Printer, 
  Download, 
  Calendar, 
  User, 
  BookOpen, 
  TrendingUp, 
  FileSpreadsheet, 
  CheckCircle,
  AlertCircle,
  Shield,
  Award,
  Clock,
  HelpCircle,
  Building
} from "lucide-react";

interface PageProps {
  params: Promise<{ reportId: string }>;
}

export default function ReportDetailsPage({ params }: PageProps) {
  const { reportId } = use(params);
  const router = useRouter();

  // Load storage states
  const [report, setReport] = useState<ReportLog | null>(null);
  const [students, setStudents] = useState<Student[]>([]);
  const [assessments, setAssessments] = useState<Assessment[]>([]);
  const [faculty, setFaculty] = useState({
    fullName: "Dr. Ramesh Sharma",
    department: "CSE",
    designation: "Professor & HOD",
    collegeName: "PSG College of Technology"
  });

  const [isLoading, setIsLoading] = useState(true);
  const [generatedTime, setGeneratedTime] = useState("");

  useEffect(() => {
    // Load metadata
    const allReports = loadReports();
    const foundReport = allReports.find(r => r.id === reportId);
    
    // Fallback if not found in history
    if (foundReport) {
      setReport(foundReport);
    } else {
      // Create a default report log dynamically
      setReport({
        id: reportId,
        name: "Departmental Assessment Outcomes Report",
        category: "Assessment",
        generatedDate: new Date().toISOString().split("T")[0],
        generatedBy: "Dr. Ramesh Sharma",
        exportType: "PDF",
        downloadCount: 1
      });
    }

    setStudents(loadStudents());
    setAssessments(loadAssessments());
    setFaculty(loadFacultyProfile());
    setGeneratedTime(new Date().toLocaleString());
    setIsLoading(false);
  }, [reportId]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = (format: "CSV" | "Excel") => {
    if (!report) return;

    let csvContent = "";
    
    // Header section
    csvContent += `Report Name,${report.name}\n`;
    csvContent += `Category,${report.category}\n`;
    csvContent += `Generated Date,${report.generatedDate}\n`;
    csvContent += `Generated By,${report.generatedBy}\n\n`;

    if (report.category === "Student" || report.category === "TopPerformers") {
      csvContent += "Rank,Roll Number,Student Name,Score,Percentage,Status\n";
      students.forEach((student, index) => {
        const isSuspended = student.status === "Suspended";
        const score = index === 0 ? 48 : index === 1 ? 42 : index === 2 ? 38 : index === 3 ? 35 : 22;
        const percentage = score ? `${(score / 50) * 100}%` : "—";
        const statusStr = isSuspended ? "DISQUALIFIED" : "SUBMITTED";
        csvContent += `"${isSuspended ? "—" : index + 1}","${student.roll}","${student.name}","${isSuspended ? "0" : score} / 50","${isSuspended ? "0%" : percentage}","${statusStr}"\n`;
      });
    } else if (report.category === "Question") {
      csvContent += "Question Description,Attempts,Correct,Incorrect,Success Rate,Avg Time,Avg Score\n";
      csvContent += `"Q1: Invert a Binary Tree","132","101","31","76.5%","24 mins","11.5 / 15"\n`;
      csvContent += `"Q2: Validate Binary Search Tree","128","87","41","67.9%","28 mins","10.8 / 15"\n`;
      csvContent += `"Q3: Dijkstra Shortest Path","85","36","49","42.3%","45 mins","9.4 / 20"\n`;
    } else if (report.category === "Batch") {
      csvContent += "Class Section,Appeared,Average Score,Pass Percentage\n";
      csvContent += `"CSE Section A","68","82.1%","95.6%"\n`;
      csvContent += `"CSE Section B","64","74.5%","89.2%"\n`;
    } else if (report.category === "Department") {
      csvContent += "Subject / Core Course,Evaluation Count,Total Audited,Success Rate,OBE Outcome Index\n";
      csvContent += `"CS201: Data Structures","4","132","92.4%","CO1 CO2 [Excellent]"\n`;
      csvContent += `"IT305: Object Oriented Programming","3","65","88.5%","CO3 [Good]"\n`;
      csvContent += `"CS304: Design & Analysis of Algorithms","2","120","76.8%","CO2 CO4 [Satisfactory]"\n`;
    } else if (report.category === "AtRisk") {
      csvContent += "Roll Number,Student Name,Avg score,Weak Subject Area,Action Plan\n";
      csvContent += `"22CSE156","Pooja Hegde","44.0%","BST Binary Trees recursion","Remedial Class assigned"\n`;
      csvContent += `"22EEE045","Vijay Krishnan","0.0%","Disqualified (Proctor Violations)","Parent-Teacher Meeting"\n`;
    } else {
      // Assessment / Semester
      csvContent += "Assessment Name,Subject,Date,Duration,Total Students,Total Marks\n";
      csvContent += `"${primaryAssessment.name}","${primaryAssessment.subject}","${primaryAssessment.date}","${primaryAssessment.duration} minutes","${students.length} students","50 Points"\n\n`;
      csvContent += "Pass Rate,Average Score,Highest Score,Lowest Score,Submission Rate\n";
      csvContent += `"92.4%","38.2 / 50","48 / 50","18 / 50","100%"\n`;
    }

    // Generate blob and trigger click download
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const filename = `${report.name.replace(/\s+/g, "_")}_export.${format === "CSV" ? "csv" : "xlsx"}`;
    
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Update download counter in storage history
    try {
      const allReports = loadReports();
      const updated = allReports.map(r => r.id === report.id ? { ...r, downloadCount: r.downloadCount + 1 } : r);
      if (typeof window !== "undefined" && window.localStorage) {
        window.localStorage.setItem("reports_history", JSON.stringify(updated));
      }
      setReport({ ...report, downloadCount: report.downloadCount + 1 });
    } catch (e) {
      console.error(e);
    }
  };

  if (isLoading || !report) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center font-sans text-xs">
        <div className="text-center space-y-2">
          <div className="w-8 h-8 border-4 border-navy-900 border-t-transparent rounded-full animate-spin mx-auto"></div>
          <p className="font-bold text-slate-500">Loading audit templates...</p>
        </div>
      </div>
    );
  }

  // Derived mock variables for templates
  const primaryAssessment = assessments[0] || {
    name: "Data Structures Practical Lab Exam",
    subject: "CS201",
    duration: 180,
    questionsCount: 3,
    assignedCount: 132,
    date: "June 17, 2026"
  };

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col font-sans text-xs text-slate-800 antialiased">
      
      {/* Top action header (hidden on A4 printout) */}
      <header className="bg-slate-900 border-b border-slate-800 text-white px-6 py-4 flex items-center justify-between sticky top-0 z-40 no-print shadow-md">
        <div className="flex items-center gap-3">
          <button 
            onClick={() => router.back()} 
            className="text-slate-400 hover:text-white transition-colors p-1.5 hover:bg-slate-850 rounded-md focus-ring flex items-center gap-1.5 font-bold"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Back to reports
          </button>
          <div className="h-4 w-[1px] bg-slate-800"></div>
          <div>
            <h1 className="font-extrabold text-white text-xs tracking-tight uppercase leading-none">
              {report.name}
            </h1>
            <p className="text-slate-400 text-[10px] mt-1 font-medium">
              Category: {report.category} Report • Authored: {report.generatedDate}
            </p>
          </div>
        </div>

        {/* Dispatch actions */}
        <div className="flex items-center gap-2">
          <button 
            onClick={() => handleDownload("CSV")}
            className="bg-slate-800 hover:bg-slate-750 text-slate-200 font-bold px-3 py-2 rounded-md flex items-center gap-1.5 transition-colors focus-ring"
          >
            <Download className="w-3.5 h-3.5 text-slate-400" /> Export CSV
          </button>
          <button 
            onClick={() => handleDownload("Excel")}
            className="bg-slate-800 hover:bg-slate-750 text-slate-200 font-bold px-3 py-2 rounded-md flex items-center gap-1.5 transition-colors focus-ring"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-450" /> Export Excel
          </button>
          <button 
            onClick={handlePrint}
            className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2 rounded-md flex items-center gap-1.5 transition-colors focus-ring shadow-xs"
          >
            <Printer className="w-3.5 h-3.5" /> Print / Export PDF
          </button>
        </div>
      </header>

      {/* The Printable A4 Page Wrapper */}
      <div className="flex-1 flex justify-center p-0 md:p-8 no-print-padding">
        
        <div className="bg-white max-w-[800px] w-full p-8 md:p-12 border border-slate-200 shadow-lg print-shadow-none print-border-none flex flex-col justify-between min-h-[1050px]">
          
          <div className="space-y-8">
            {/* 1. PDF Header Area */}
            <div className="flex items-start justify-between border-b-2 border-slate-900 pb-5">
              <div className="flex items-center gap-4">
                {/* SVG Institutional Emblem Logo */}
                <div className="bg-slate-900 text-white p-3 rounded-lg border border-slate-850 flex items-center justify-center shrink-0">
                  <Shield className="w-8 h-8 text-blue-500 fill-blue-500/10" />
                </div>
                <div>
                  <h2 className="font-extrabold text-sm tracking-tight text-slate-950 uppercase leading-snug">
                    {faculty.collegeName.toUpperCase()}
                  </h2>
                  <p className="text-[10px] text-slate-500 uppercase tracking-widest font-bold">
                    Department of {faculty.department}
                  </p>
                  <p className="text-[9px] text-slate-400 mt-0.5">
                    Accreditation Auditing & Quality Standard Folder outcomes
                  </p>
                </div>
              </div>

              <div className="text-right font-mono text-[9px] text-slate-450 uppercase leading-normal">
                <p>Doc ID: <span className="font-bold text-slate-900">{report.id.toUpperCase()}</span></p>
                <p>Run: {report.generatedDate}</p>
                <p>Type: {report.category}</p>
              </div>
            </div>

            {/* Title / Description */}
            <div className="text-center space-y-1.5">
              <h3 className="text-base font-black text-slate-950 uppercase tracking-tight">
                {report.name.toUpperCase()}
              </h3>
              <p className="text-[10px] text-slate-500 font-medium italic max-w-xl mx-auto">
                This report document lists internal evaluation data compiled from secure sandboxed programming assessments. Content represents verified student compiler sessions.
              </p>
            </div>

            {/* ========================================================================= */}
            {/* TEMPLATE A: ASSESSMENT REPORT */}
            {(report.category === "Assessment" || report.category === "Semester") && (
              <div className="space-y-6">
                {/* Parameters */}
                <div className="bg-slate-50 p-4 border border-slate-200 rounded-lg space-y-3">
                  <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450 border-b border-slate-200 pb-1.5">
                    1. Assessment Parameters
                  </h4>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-y-3 gap-x-6 text-[10px]">
                    <div>
                      <span className="text-slate-400 font-semibold block">Evaluation Name:</span>
                      <span className="font-bold text-slate-900">{primaryAssessment.name}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Subject Code:</span>
                      <span className="font-bold text-slate-900 font-mono">{primaryAssessment.subject}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Evaluation Date:</span>
                      <span className="font-bold text-slate-900 font-mono">{primaryAssessment.date}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Duration limit:</span>
                      <span className="font-bold text-slate-900 font-mono">{primaryAssessment.duration} minutes</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Assigned Candidates:</span>
                      <span className="font-bold text-slate-900 font-mono">{students.length} students</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Assessment Marks:</span>
                      <span className="font-bold text-slate-900 font-mono">50 Points (max)</span>
                    </div>
                  </div>
                </div>

                {/* Summary Metrics */}
                <div className="space-y-3">
                  <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450 pb-0.5">
                    2. Outcome Summary Metrics
                  </h4>
                  
                  <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 font-mono">
                    <div className="border border-slate-200 p-3 rounded text-center">
                      <span className="text-slate-455 text-[8px] font-bold block uppercase">Pass Rate</span>
                      <span className="text-lg font-black text-emerald-850 block mt-1">92.4%</span>
                    </div>
                    <div className="border border-slate-200 p-3 rounded text-center">
                      <span className="text-slate-455 text-[8px] font-bold block uppercase">Avg Score</span>
                      <span className="text-lg font-black text-slate-900 block mt-1">38.2 / 50</span>
                    </div>
                    <div className="border border-slate-200 p-3 rounded text-center">
                      <span className="text-slate-455 text-[8px] font-bold block uppercase">Highest</span>
                      <span className="text-lg font-black text-blue-800 block mt-1">48 / 50</span>
                    </div>
                    <div className="border border-slate-200 p-3 rounded text-center">
                      <span className="text-slate-455 text-[8px] font-bold block uppercase">Lowest</span>
                      <span className="text-lg font-black text-rose-800 block mt-1">18 / 50</span>
                    </div>
                    <div className="border border-slate-200 p-3 rounded text-center">
                      <span className="text-slate-455 text-[8px] font-bold block uppercase">Submit Rate</span>
                      <span className="text-lg font-black text-slate-900 block mt-1">100%</span>
                    </div>
                  </div>
                </div>

                {/* Section performance distributions chart */}
                <div className="border border-slate-200 p-4 rounded-lg space-y-3">
                  <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450 flex items-center gap-1 pb-1 border-b border-slate-100">
                    <Building className="w-3.5 h-3.5 text-slate-400" /> Grade Distribution Analysis
                  </h4>
                  
                  <div className="space-y-2 pt-1">
                    {/* Bar A */}
                    <div className="space-y-1">
                      <div className="flex justify-between text-[9px] font-bold uppercase">
                        <span>Excellent (&gt; 90% score)</span>
                        <span className="font-mono">35% (46 students)</span>
                      </div>
                      <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-600 rounded-full" style={{ width: "35%" }}></div>
                      </div>
                    </div>

                    {/* Bar B */}
                    <div className="space-y-1">
                      <div className="flex justify-between text-[9px] font-bold uppercase">
                        <span>Good (70% - 90% score)</span>
                        <span className="font-mono">42% (55 students)</span>
                      </div>
                      <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                        <div className="h-full bg-emerald-600 rounded-full" style={{ width: "42%" }}></div>
                      </div>
                    </div>

                    {/* Bar C */}
                    <div className="space-y-1">
                      <div className="flex justify-between text-[9px] font-bold uppercase">
                        <span>Satisfactory (50% - 70% score)</span>
                        <span className="font-mono">15% (20 students)</span>
                      </div>
                      <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                        <div className="h-full bg-amber-500 rounded-full" style={{ width: "15%" }}></div>
                      </div>
                    </div>

                    {/* Bar D */}
                    <div className="space-y-1">
                      <div className="flex justify-between text-[9px] font-bold uppercase text-rose-700">
                        <span>At Risk (&lt; 50% score)</span>
                        <span className="font-mono">8% (11 students)</span>
                      </div>
                      <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                        <div className="h-full bg-rose-600 rounded-full" style={{ width: "8%" }}></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* ========================================================================= */}
            {/* TEMPLATE B: STUDENT PERFORMANCE REPORT */}
            {(report.category === "Student" || report.category === "TopPerformers") && (
              <div className="space-y-4">
                <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450">
                  Detailed Student Performance & Ranks
                </h4>

                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <table className="w-full text-left border-collapse text-[10px]">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[8px]">
                        <th className="py-2 px-3 text-center">Rank</th>
                        <th className="py-2 px-3">Roll Number</th>
                        <th className="py-2 px-3">Student Name</th>
                        <th className="py-2 px-3 text-center">Score</th>
                        <th className="py-2 px-3 text-center">Percentage</th>
                        <th className="py-2 px-3 text-right">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-150 font-mono">
                      {students.map((student, index) => {
                        // Dynamically map mock ranking/scores
                        const isSuspended = student.status === "Suspended";
                        const score = index === 0 ? 48 : index === 1 ? 42 : index === 2 ? 38 : index === 3 ? 35 : 22;
                        const percentage = score ? `${(score / 50) * 100}%` : "—";
                        
                        return (
                          <tr key={student.id} className="hover:bg-slate-50/50">
                            <td className="py-2 px-3 text-center font-bold text-slate-900">
                              {isSuspended ? "—" : index + 1}
                            </td>
                            <td className="py-2 px-3 font-bold text-slate-800">{student.roll}</td>
                            <td className="py-2 px-3 font-sans font-medium text-slate-900">{student.name}</td>
                            <td className="py-2 px-3 text-center font-bold text-slate-900">
                              {isSuspended ? "00" : `${score} / 50`}
                            </td>
                            <td className="py-2 px-3 text-center text-slate-700">
                              {isSuspended ? "0%" : percentage}
                            </td>
                            <td className="py-2 px-3 text-right">
                              <span className={`px-2 py-0.5 rounded text-[8px] font-bold font-sans uppercase ${
                                isSuspended ? "bg-rose-50 text-rose-800 border border-rose-100" : "bg-emerald-50 text-emerald-800 border border-emerald-100"
                              }`}>
                                {isSuspended ? "DISQUALIFIED" : "SUBMITTED"}
                              </span>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* ========================================================================= */}
            {/* TEMPLATE C: QUESTION ANALYSIS REPORT */}
            {report.category === "Question" && (
              <div className="space-y-4">
                <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450">
                  Question-wise Performance & Error Indices
                </h4>

                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <table className="w-full text-left border-collapse text-[10px]">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[8px]">
                        <th className="py-2 px-3">Question Description</th>
                        <th className="py-2 px-3 text-center">Attempts</th>
                        <th className="py-2 px-3 text-center">Correct</th>
                        <th className="py-2 px-3 text-center">Incorrect</th>
                        <th className="py-2 px-3 text-center">Success Rate</th>
                        <th className="py-2 px-3 text-center">Avg Time</th>
                        <th className="py-2 px-3 text-right">Avg Score</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-150 font-mono">
                      <tr className="hover:bg-slate-50/50">
                        <td className="py-2.5 px-3 font-sans font-bold text-slate-900">Q1: Invert a Binary Tree</td>
                        <td className="py-2.5 px-3 text-center">132</td>
                        <td className="py-2.5 px-3 text-center text-emerald-800 font-bold">101</td>
                        <td className="py-2.5 px-3 text-center text-rose-800">31</td>
                        <td className="py-2.5 px-3 text-center font-bold">76.5%</td>
                        <td className="py-2.5 px-3 text-center text-slate-500">24 mins</td>
                        <td className="py-2.5 px-3 text-right font-bold text-slate-800">11.5 / 15</td>
                      </tr>
                      <tr className="hover:bg-slate-50/50">
                        <td className="py-2.5 px-3 font-sans font-bold text-slate-900">Q2: Validate Binary Search Tree</td>
                        <td className="py-2.5 px-3 text-center">128</td>
                        <td className="py-2.5 px-3 text-center text-emerald-800 font-bold">87</td>
                        <td className="py-2.5 px-3 text-center text-rose-800">41</td>
                        <td className="py-2.5 px-3 text-center font-bold">67.9%</td>
                        <td className="py-2.5 px-3 text-center text-slate-500">28 mins</td>
                        <td className="py-2.5 px-3 text-right font-bold text-slate-800">10.8 / 15</td>
                      </tr>
                      <tr className="hover:bg-slate-50/50">
                        <td className="py-2.5 px-3 font-sans font-bold text-slate-900">Q3: Dijkstra Shortest Path</td>
                        <td className="py-2.5 px-3 text-center">85</td>
                        <td className="py-2.5 px-3 text-center text-emerald-800 font-bold">36</td>
                        <td className="py-2.5 px-3 text-center text-rose-800">49</td>
                        <td className="py-2.5 px-3 text-center font-bold text-slate-900">42.3%</td>
                        <td className="py-2.5 px-3 text-center text-slate-500">45 mins</td>
                        <td className="py-2.5 px-3 text-right font-bold text-slate-800">9.4 / 20</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* ========================================================================= */}
            {/* TEMPLATE D: BATCH REPORT */}
            {report.category === "Batch" && (
              <div className="space-y-6">
                <div className="bg-slate-50 p-4 border border-slate-200 rounded-lg space-y-3">
                  <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450 border-b border-slate-200 pb-1.5">
                    Batch Details
                  </h4>
                  <div className="grid grid-cols-2 gap-y-3 text-[10px]">
                    <div>
                      <span className="text-slate-400 font-semibold block">Academic Batch:</span>
                      <span className="font-bold text-slate-900">2026 Graduating Cohort (CSE)</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Total Enrollment:</span>
                      <span className="font-bold text-slate-900 font-mono">132 candidates</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Batch Avg score:</span>
                      <span className="font-bold text-slate-900 font-mono">78.4%</span>
                    </div>
                    <div>
                      <span className="text-slate-400 font-semibold block">Placement Eligible (&gt; 60%):</span>
                      <span className="font-bold text-emerald-800 font-mono">122 candidates (92.4%)</span>
                    </div>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450 pb-0.5">
                    Section Outcomes Comparison
                  </h4>
                  
                  <div className="border border-slate-200 rounded-lg overflow-hidden">
                    <table className="w-full text-left border-collapse text-[10px]">
                      <thead>
                        <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[8px]">
                          <th className="py-2 px-3">Class Section</th>
                          <th className="py-2 px-3 text-center">Appeared</th>
                          <th className="py-2 px-3 text-center font-bold">Average Score</th>
                          <th className="py-2 px-3 text-right">Pass Percentage</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-150 font-mono">
                        <tr>
                          <td className="py-2 px-3 font-sans font-semibold">CSE Section A</td>
                          <td className="py-2 px-3 text-center">68</td>
                          <td className="py-2 px-3 text-center font-bold">82.1%</td>
                          <td className="py-2 px-3 text-right text-emerald-800 font-bold">95.6%</td>
                        </tr>
                        <tr>
                          <td className="py-2 px-3 font-sans font-semibold">CSE Section B</td>
                          <td className="py-2 px-3 text-center">64</td>
                          <td className="py-2 px-3 text-center font-bold">74.5%</td>
                          <td className="py-2 px-3 text-right text-emerald-800 font-bold">89.2%</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}

            {/* ========================================================================= */}
            {/* TEMPLATE E: DEPARTMENT REPORT */}
            {report.category === "Department" && (
              <div className="space-y-4">
                <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-slate-450">
                  Department-wise Accreditation Averages
                </h4>

                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <table className="w-full text-left border-collapse text-[10px]">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[8px]">
                        <th className="py-2.5 px-3">Subject / Core Course</th>
                        <th className="py-2.5 px-3 text-center">Evaluation Count</th>
                        <th className="py-2.5 px-3 text-center">Total Audited</th>
                        <th className="py-2.5 px-3 text-center">Success Rate</th>
                        <th className="py-2.5 px-3 text-right">OBE Outcome Index</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-150 font-mono">
                      <tr>
                        <td className="py-2 px-3 font-sans font-bold text-slate-900">CS201: Data Structures</td>
                        <td className="py-2 px-3 text-center">4</td>
                        <td className="py-2 px-3 text-center">132</td>
                        <td className="py-2 px-3 text-center text-emerald-800">92.4%</td>
                        <td className="py-2 px-3 text-right font-bold text-slate-800">CO1, CO2 [Excellent]</td>
                      </tr>
                      <tr>
                        <td className="py-2 px-3 font-sans font-bold text-slate-900">IT305: Object Oriented Programming</td>
                        <td className="py-2 px-3 text-center">3</td>
                        <td className="py-2 px-3 text-center">65</td>
                        <td className="py-2 px-3 text-center text-emerald-800">88.5%</td>
                        <td className="py-2 px-3 text-right font-bold text-slate-800">CO3 [Good]</td>
                      </tr>
                      <tr>
                        <td className="py-2 px-3 font-sans font-bold text-slate-900">CS304: Design & Analysis of Algorithms</td>
                        <td className="py-2 px-3 text-center">2</td>
                        <td className="py-2 px-3 text-center">120</td>
                        <td className="py-2 px-3 text-center text-emerald-800">76.8%</td>
                        <td className="py-2 px-3 text-right font-bold text-slate-800">CO2, CO4 [Satisfactory]</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* ========================================================================= */}
            {/* TEMPLATE F: AT-RISK STUDENTS REPORT */}
            {report.category === "AtRisk" && (
              <div className="space-y-4">
                <h4 className="font-extrabold text-[9px] tracking-wider uppercase text-rose-700">
                  Targeted Intervention: Students Scoring below 50% Threshold
                </h4>

                <div className="border border-rose-200 rounded-lg overflow-hidden">
                  <table className="w-full text-left border-collapse text-[10px]">
                    <thead>
                      <tr className="bg-rose-50/50 border-b border-rose-200 text-rose-800 font-bold uppercase text-[8px]">
                        <th className="py-2 px-3">Roll Number</th>
                        <th className="py-2 px-3">Student Name</th>
                        <th className="py-2 px-3 text-center font-bold">Avg score</th>
                        <th className="py-2 px-3">Weak Subject Area</th>
                        <th className="py-2 px-3 text-right">Action Plan</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-rose-100 font-mono">
                      <tr>
                        <td className="py-2.5 px-3 font-bold text-slate-850">22CSE156</td>
                        <td className="py-2.5 px-3 font-sans font-medium text-slate-900">Pooja Hegde</td>
                        <td className="py-2.5 px-3 text-center text-rose-700 font-bold">44.0%</td>
                        <td className="py-2.5 px-3 font-sans text-slate-600">BST, Binary Trees recursion</td>
                        <td className="py-2.5 px-3 text-right font-sans text-blue-700 font-bold">Remedial Class assigned</td>
                      </tr>
                      <tr>
                        <td className="py-2.5 px-3 font-bold text-slate-850">22EEE045</td>
                        <td className="py-2.5 px-3 font-sans font-medium text-slate-900">Vijay Krishnan</td>
                        <td className="py-2.5 px-3 text-center text-rose-700 font-bold">0.0%</td>
                        <td className="py-2.5 px-3 font-sans text-slate-600">Disqualified (Proctor Violations)</td>
                        <td className="py-2.5 px-3 text-right font-sans text-rose-700 font-bold">Parent-Teacher Meeting</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            )}

          </div>

          {/* 3. Faculty Signatures and Timestamp (at the bottom) */}
          <div className="pt-8 border-t border-slate-200 mt-12 space-y-6">
            <div className="flex justify-between items-center text-[10px] text-slate-650">
              <span>Report Generated by: <span className="font-bold text-slate-900">{report.generatedBy}</span></span>
              <span>Timestamp: <span className="font-mono text-slate-900">{generatedTime}</span></span>
            </div>

            {/* Signature Area */}
            <div className="flex justify-between pt-8 text-[10px] font-sans font-medium">
              <div className="w-48 text-center space-y-1">
                <div className="border-t border-slate-400 pt-2">
                  <p className="font-bold text-slate-900">Faculty Coordinator</p>
                  <p className="text-slate-400 text-[8px] uppercase">PSG Tech Evaluator Node</p>
                </div>
              </div>

              <div className="w-48 text-center space-y-1">
                <div className="border-t border-slate-400 pt-2">
                  <p className="font-bold text-slate-900">HOD / Academic Chair</p>
                  <p className="text-slate-400 text-[8px] uppercase">Approved signature seal</p>
                </div>
              </div>
            </div>

            {/* Security Audit Cryptographic Hash footer */}
            <div className="bg-slate-50 border border-slate-200 p-2.5 rounded font-mono text-[8px] text-slate-450 leading-normal text-center select-all">
              SECURE SHA256 PLATFORM GRADER VERIFICATION HASH: {Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}
            </div>
          </div>

        </div>
        
      </div>

    </div>
  );
}
